### ISSUE TITLE
Sprite 핸들링 클래스 선정 이슈

### ISSUE THREAD

**Issue by PRKM** [jwqe764241/GameFramework#3]
1. 기존에는 Graphics 클래스에 Sprite를 다룰 수 있는 멤버 변수를 만들어서 관리했다.
2. 그런데 앞으로도 이런 방식으로 해주면 이후 **레벨이 점점 늘어나면** Graphics가 **더 복잡해질 위험성**이 있음.

**Comment by PRKM** [comment]
Sprite 관리 코드는 Sprite를 관리하는 클래스인 SpriteSheet 클래스를 별도로 작성하여 관리하도록 설정할 것임.

**Comment by jwqe764241** [comment]
https://en.wikipedia.org/wiki/God_object

Graphics에 넣으면 위 항목과 같은 God Object가 되고, 인터페이스를 따로 빼놓기 위해 friend 하는것도 조금
 그렇기 때문에 별도 클래스에 넣는게 맞다고 생각함
