### ISSUE TITLE
Player, SpriteSheet관련 이슈

### ISSUE THREAD

**Issue by PRKM** [jwqe764241/GameFramework#4]
1. SpriteSheet에서 플레이어의 스프라이트 사이즈 정보(sprite width, height)를 담고 있는 것이 맞나? 아니면 Player가 가지고 잇는 것인가?
2. 지금 Player의 생성자가 Game에서 생성되고, 오버라이딩된 것이 플레이어의 위치인데, 추가로 거기에 Graphics 객체도 받아올 수 있게 하면 안되나?
  a. IActor(일단은 상속받은 Player) 클래스에서 SpriteSheet 객체를 생성하여 관리하려고 위 방법을 제안하는거임

**Comment by jwqe764241** [comment]
1. SpriteSheet가 단지 그 모습을 그려주는, 즉 형태에 대해서 서술하는 클래스 이면 스프라이트 사이즈 정보를 담는게 맞다고 봄

2.일단 Game에 있는 렌더 리스트는 전부 Level(맵)에 넣을 계획임, 일단은 시도 해보고 생각하는게 좋다고 봄
