### ISSUE TITLE
Keyboard 클래스의 문제점

### ISSUE THREAD

**Issue by jwqe764241** [jwqe764241/GameFramework#5]
테스트 도중 방향 전환이 매끄럽지 않음

그 이유는 윈도우에서 제공하는 입력 방법을 사용하기 때문임

메시지큐에 적재된 후 꺼내는 거라 키 교체 반응이 느림

EX)
RIGHT 키를 누르다가 그 상태에서 LEFT 키로 바꾸어서 입력할 시 딜레이가 생긴 후 반복입력이 된다.

**Comment by PRKM** [comment]
http://ppparkje.tistory.com/24
봤을수도 있는데, 혹시 모르니까 이 링크도 참고해보셈
ㄴ 넹

**Comment by jwqe764241** [comment]
DX_Input 이 Direct Input 으로 고속 입력을 받을 수 있게 만든 클래스입니다. 문제 없이 동작 잘 되고 합니다.
