### ISSUE TITLE
윈도우 Resizing과 RenderTarget 크기 변경..

### ISSUE THREAD

**Issue by jwqe764241** [jwqe764241/GameFramework#6]
![1](https://cloud.githubusercontent.com/assets/13945127/24072767/7549b594-0c2f-11e7-9859-ebff82c22ff4.JPG)

초기 상태에서  윈도우 크기를 늘리거나 줄이면 다음과 같이 된다.

![2](https://cloud.githubusercontent.com/assets/13945127/24072773/874acb16-0c2f-11e7-9921-5033924599f1.JPG)

레벨 작업 하면서 생각해 봤는데 2가지 방법이 있습니다.

1. 그냥 윈도우를 못 줄이게 하면 됨

2. RenderTarget의 Resize 함수를 이용하여 크기를 재설정 하는 것
 : 이걸로 하였을 때 다음과 같이 해결됨

![3](https://cloud.githubusercontent.com/assets/13945127/24072785/c0506876-0c2f-11e7-8dc4-26c184635031.JPG)

그런데 위의 방법은 매 프레임마다 GetWindowRect를 이용하여 윈도우 사이즈를 구한다음 RenderTarget 사이즈를 바꿔주는 것이라 Frame의 윈도우 프로시저에서 WM_SIZE 메시지가 발생 되었을 때 호출하고 싶음

Frame에 Graphics 포인터 두고 Game 이 초기화 할 때 Game의 Graphics 주소를 Frame의 Graphics에 넣어주고 WM_SIZE 메시지 발생 시 Graphics에 추가한 RenderRender 함수를 호출하여 RenderTarget 크기를 바꾸어 줄려고 하는데 그러면 코드가 Frame 초기화 하고 Game의 Graphics 초기화 하고 또 Frame의 Graphics를 초기화된 Game의 Graphics 주소로 초기화 해주는 식이라서 과연 이렇게 해야하는게 맞는가 싶음...

자세한건 Level 브랜치 확인
(TODO:ISSUE#6으로 해놓았으니 작업 목록에서 확인 가능합니다)

작업목록에서 ISSUE#6 검색

**Comment by PRKM** [comment]
해당 이슈 문서를 보고 궁금해진 건데, 명확한 이유를 다시 듣고 싶어서 질문을 올립니다.

1. 왜 굳이 Message 받은 것을 처리하는 **MsgProc 함수**와 메시지를 먼저 받는 **Loop 함수**가 있는 **클래스가 서로 다른 것**인가?(현재 MsgProc은 Frame, Loop 함수는 Game 함수에 있습니다)

제가 생각한 방법은 다음과 같습니다.

> S1. Frame::MsgProc() 함수를 Game 클래스로 옮긴다.

위 제안의 이유는 현 시점에서는 hwnd 객체를 넘겨주거나 풀어주는 작업을 하는 것을 빼면 Frame이 **Window를 설정**하고 **메시지에 대한 분기점만 나눠주는 역할**만 하기 때문에 그렇게 _큰 역할을 맡고 있지 않다고 생각_해서 위 방안을 제안한 것입니다.

> S2. Game 클래스에 Frame 클래스를 그냥 합친다.

제안 1의 연장선상에 서 있는 제안입니다. **Frame의 역할 자체가 너무 작기 때문**에 Frame을 Game에 합친다고 해서 Game 클래스의 비중 문제는 발생하지 않을 것이라 생각했기 때문에 제안하였습니다.

위 두개 중 하나의 제안이라도 적용하였을 경우, 아래의 장점이 따릅니다.
1. **MsgProc에서 Graphics의 OnResize()에 접근**할 수 있다.(Game의 클래스 멤버변수로 Graphics 객체가 있기 때문)

**Comment by jwqe764241** [comment]
사실상 게임 Loop가 돌았다는 것은 게임이 시작되었다는걸 의미하기 때문에 당연하게도 Loop를 Game에 놓게 되었습니다.

일단 Frame과 Game을 따로 둔 이유는 나중을 위해서임을 말하고 싶습니다.

이 프로젝트는 아직 진행된지 얼마 안됬으며 제대로된 게임이 될 때 까지 아직 멀었음을 알려드립니다.

제 생각은 후에 추가될 많은 기능들 ( 프로젝타일, 콜리전, 장애물, 레벨, 게임종료 등등등 )이 추가될 수록 게임 을 전담하는 Game 클래스가 커진다는 것을 감안하셔야 합니다. 그렇기 때문에 조금이나마 역활을 분산시키기 위하여 컨트롤러를 놓는 것이지요

1번은 좋은 선택이 될 순 있겠지만 2번은 추후 추가될 컨트롤러 등을 보았을때 해서는 안된다고 봅니다.

일단 자러갑니다. 내일 생각해 보고 이슈 닫겠습니다.

**Comment by jwqe764241** [comment]
그냥 Graphics를 싱글톤으로 만들어 버릴까 생각중입니다. 흠....

**Comment by jwqe764241** [comment]
일단 분리하는것과 다른점은 없지만 중첩 클래스로 만들고 (보기 편하게;;) Graphics 포인터로 Game의 Graphics로 넘겨주어서 해결 하였습니다만.. 그렇게 좋은 방법이라고 생각이 들진 않습니다 ㅠ
